// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBhg5Zz_5eS35okMHPfhkBukKB06HvB00',
    appId: '1:543650198989:web:7c55b14be99278b3fc4084',
    messagingSenderId: '543650198989',
    projectId: 'rollcall-02',
    authDomain: 'rollcall-02.firebaseapp.com',
    storageBucket: 'rollcall-02.firebasestorage.app',
    measurementId: 'G-6YM0Z5V9PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjfVdGCisDzrlRpap7-LyTaXiejVaQgjw',
    appId: '1:543650198989:android:5c41fc579f7ffdb6fc4084',
    messagingSenderId: '543650198989',
    projectId: 'rollcall-02',
    storageBucket: 'rollcall-02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN_wMnv61UG4FvzNYpCsWl2z9vALeCOjM',
    appId: '1:543650198989:ios:baa22bfe3503be57fc4084',
    messagingSenderId: '543650198989',
    projectId: 'rollcall-02',
    storageBucket: 'rollcall-02.firebasestorage.app',
    iosBundleId: 'com.example.rollcall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN_wMnv61UG4FvzNYpCsWl2z9vALeCOjM',
    appId: '1:543650198989:ios:baa22bfe3503be57fc4084',
    messagingSenderId: '543650198989',
    projectId: 'rollcall-02',
    storageBucket: 'rollcall-02.firebasestorage.app',
    iosBundleId: 'com.example.rollcall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBhg5Zz_5eS35okMHPfhkBukKB06HvB00',
    appId: '1:543650198989:web:8d6ed1d8541771effc4084',
    messagingSenderId: '543650198989',
    projectId: 'rollcall-02',
    authDomain: 'rollcall-02.firebaseapp.com',
    storageBucket: 'rollcall-02.firebasestorage.app',
    measurementId: 'G-1X480G8CW6',
  );
}
